# Generated by Django 3.2.6 on 2021-08-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_users_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email_id',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
